import Header from "@/components/ui/Header";
import Sidebar from "@/components/ui/Sidebar";
import type { Metadata } from "next";
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<main className="relative">
			<Header />
			<div className="flex screen-height">
				<Sidebar />
				{children}
			</div>
		</main>
	);
}
