import Header from "@/components/ui/Header";
import Sidebar from "@/components/ui/Sidebar";
import InitUser from "@/lib/InitUser";
import type { Metadata } from "next";
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div className="flex flex-col relative h-screen">
			<Header />
			<div className="flex flex-1 overflow-hidden">
				<Sidebar />
				<div className="flex-1 overflow-y-auto ">
					<InitUser />
					{children}
				</div>
			</div>
		</div>
	);
}
